### ISSUE TITLE
Question: how to set the buffer id background?

### ISSUE THREAD

**Issue by azer** [milkypostman/powerline#143]
Hi there,

I turned off everything except the buffer id, and would like to set its background as the default background of powerline. 

I tried bunch of variables but couldn't get it working, which variable we need to set to change the background color of buffer id ? 

Screenshot: 

![](https://cldup.com/qb1gylyB96.png)

**Comment by c-alpha** [comment]
You'll have to set the mode-line face because that's what is used for rendering the buffer id. This will also change the mode line of speedbar, RefTeX, and similar, which may or may not be what you intend.

An alternative might be my PR #146, which makes the buffer id also customisable, but without affecting speedbar etc. mode lines.

**Comment by c-alpha** [comment]
@azer, since PR #146 has been merged (adding the configurability you asked for), it seems we can close this issue now?

**Comment by azer** [comment]
Thanks @c-alpha
