### ISSUE TITLE
Get loop list warning when doing native compilation

### ISSUE THREAD

**Issue by rayw000** [milkypostman/powerline#187]
I'm trying to native compile `powerline.el` on `Emacs 28.0.50`, this warning
```
/path/to/elpa/powerline-20210313.1621/powerline.el: Error: List contains a loop ("22", . #0)
```
makes `powerline` failed to compile.

Currently I add regexp `powerline` into `comp-deferred-compilation-deny-list` to walk around this issue.
```emacs-lisp
(setq comp-deferred-compilation-deny-list '("powerline"))
```

**Comment by milkypostman** [comment]
any idea what's causing this? I've not got the time to maintain this package right now but there are others lurking that will hopefully help out.

**Comment by rayw000** [comment]
> any idea what's causing this? I've not got the time to maintain this package right now but there are others lurking that will hopefully help out.

I'd like to take a look when I have time. 😃

**Comment by rayw000** [comment]
I found that some of the `pl/*` functions in `pl/memoize` called with different arguments may complain about the "loop list", such as `(pl/bar right)` and `(pl/brace left)`, but not all.
https://github.com/milkypostman/powerline/blob/cfff1cfe63793ea1a8bcfcae50c296558384cf08/powerline.el#L218-L257
Seems that these functions are all invoking `pl/pattern-defun`. I'll do some further job when I have time.
https://github.com/milkypostman/powerline/blob/cfff1cfe63793ea1a8bcfcae50c296558384cf08/powerline-separators.el#L129-L167

**Comment by wyuenho** [comment]
It's an error, it's preventing the gcc jit from compiling powerline, if any package needs a speed boost, powerline is definitely it as it one of the major bottleneck during scrolling.

**Comment by milkypostman** [comment]
oh my bad. well I am not really maintaining this anymore. if there are a lot of people upset I guess I'd come out of retirement but prefer a patch. just being honest about my time.

**Comment by milkypostman** [comment]
Relevant code:

https://github.com/milkypostman/powerline/blob/cfff1cfe63793ea1a8bcfcae50c296558384cf08/powerline-separators.el#L109-L127

The idea is that patterns have up to 5 lines,

- pattern
- header
- footer
- second pattern
- center

this allows one to generate glyphs in the powerline using pixels like,

```
header pixels
pattern pixels
pattern pixels
pattern pixels
pattern pixels
center pixels
second pattern pixels
second pattern pixels
second pattern pixels
second pattern pixels
footer pixels
```

This, even though *pattern pixels* only needs to specified once, it may need to be printed multiple times. The "hack" in the code I linked makes it so the list is infinite so it can keep getting printed `pattern-height-sym` times using `cl-subseq`.

So the fix is to either put a loop in there, or generate the list after you already know `pattern-height-sym`.

**Comment by milkypostman** [comment]
I'm happy to keep helping with this and review the code but it's the testing I don't really have time for.
